version: 2
# root keys are branch name and target is where the Dockerfile is located
"ruby-231/ubuntu2004":
  target: "ruby_231/ubuntu2004"
  ruby_version: ruby-231
  os_version: ubuntu-2004
  ruby_manager: rvm
  tags:
    - ruby_version
    - os_version
    - ruby_manager
"ruby-2410/ubuntu2004":
  target: "ruby_2410/ubuntu2004"
  ruby_version: ruby-2410
  os_version: ubuntu-2004
  ruby_manager: rvm
  tags:
    - ruby_version
    - os_version
    - ruby_manager
"ruby-269/ubuntu2004":
  target: "ruby_269/ubuntu2004"
  ruby_version: ruby-269
  os_version: ubuntu-2004
  ruby_manager: rvm
  tags:
    - ruby_version
    - os_version
    - ruby_manager